version: '3.8'

services:
  employeemanagement:
    build:
      context: ./EmployeeManagement
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY-}employeemanagement

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: dbmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p1g4@7x3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: